server:
  port: 9000
#  servlet:
#    context-path:
mybatis:
  mapper-locations: classpath:mapper/sys/*.xml,classpath:mapper/materialqt/*.xml
mybatis-plus:
  global-config:
    db-config:
      db-type: MYSQL
spring:
  profiles:
    active: app,redis,timetask
  datasource:
    name: datasource
    url: jdbc:mysql://rm-2ze4k28zf091lp6s6wo.mysql.rds.aliyuncs.com:3306/material?useUnicode=true&amp;characterEncoding=UTF-8&allowMultiQueries=true
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: feison_db_123
    tomcat:
      max-active: 5
      min-idle: 2
      max-idle: 5
      initial-size: 2
      test-on-borrow: true
      test-on-return: false
      max-wait: 3000
  aop:
    proxy-target-class: true
    auto: true

controller.scanPackage: com.edgedo


